apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverse-words
  labels:
    app: reverse-words
spec:
  template:
    spec:
      containers:
      - name: reverse-words
        image: quay.io/mihaime/tekton-reversewords:3f44e661130e14c97933d88e141ab0532fb4bae3
        env:
        - name: RELEASE
          value: "Production release"
        - $patch: replace
