apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverse-words
  labels:
    app: reverse-words
spec:
  template:
    spec:
      containers:
      - name: reverse-words
        image: quay.io/mihaime/tekton-reversewords:c615225e15f2696fe01857c63f73b579618fa3c3
        env:
        - name: RELEASE
          value: "Production release"
        - $patch: replace
