apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: trigger-stage
spec:
  inputs:
    resources:
    - name: argosource
      type: git
    - name: source
      type: git
    params:
    - name: IMAGE_TAG
      description: Tag for the built image
      default: latest

  steps:
  - name: argo-stage
    workingdir: /workspace/argosource
    image: ubuntu 
    script: |
      #!/bin/bash
      echo "Installing GIT Core"
      apt-get -y update
      apt-get -y install git-core screen
      echo "Setting basic GIT params"
      git config --global user.email "lists@mihai.tech"
      git config --global user.name "mihaime"
      git fetch
      git branch -a
      git checkout stage
      echo "Updating Deployment for Argo"
      sed -i  "s/\(.*:.*:\).*/\1$(cat /workspace/source/.git/refs/heads/master)/" deployment.yaml
      git add deployment.yaml
      git commit -m "adjusted stage to new container image $(cat /workspace/source/.git/refs/heads/master)"
      git push || { echo "failed to push"; exit 1; }
      echo "Finished argo stage"
    securityContext:
      privileged: true
