apiVersion: v1
kind: Secret
metadata:
  name: argo-crd
  annotations:
    tekton.dev/git-0: https://github.com # Described below
type: kubernetes.io/basic-auth
stringData:
  username: mihaime
  password: Mihai4HPE-neah!
---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: trigger-stage
spec:
  inputs:
    resources:
    - name: argosource
      type: git
    - name: image
      type: image
    params:
    - name: IMAGE_TAG
      description: Tag for the built image
      default: latest

  steps:
  - name: argo-stage
    image: quay.io/buildah/upstream
    workingdir: /workspace/argosource
    script: |
      #!/bin/bash
      echo "Finished argo stage"
    securityContext:
      privileged: true
